# We're using version 3.7 of the Docker Compose file format
# https://maximorlov.com/install-mysql-with-phpmyadmin-using-docker/
version: '3'

# Define services/containers
services:
  # MySQL container
  mysql:
    # Use mysql:8.0.19 image
    image: mysql:8.0.19
    # Connect to "my-network" network, as defined below
    networks:
      - mysql-network
    ports:
      - "3306:3306"
    # Pass a list of environment variables to the container
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
  # phpMyAdmin container
  phpmyadmin:
    # Use phpmyadmin/phpmyadmin:5.0.2 image
    image: phpmyadmin/phpmyadmin:5.0.2
    # Connect to "my-network" network, as defined below
    networks:
      - mysql-network
    # Map port 8080 on the host to port 80 inside the container
    # Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "8080:80"
    # Pass a list of environment variables to the container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    # Wait for "mysql" container to start first 
    depends_on:
      - mysql

# Define networks
networks:
  mysql-network:
volumes:
  mysql-data: